### PR TITLE
Switch to python 3.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by aclements** [comment]
Hi @petterreinholdtsen. What's the motivation for doing this? Your commit message didn't say.

**Comment by petterreinholdtsen** [comment]
[Austin Clements]
> Hi @petterreinholdtsen. What's the motivation for doing this? Your
> commit message didn't say.

My motivation is to make sure the build work independent of python
version, to make sure the debian package can build depend on python
without a specific version number.  Without the patch, the package build
fail to work with python >= 3.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Would you prefer to just call 'python' instead of replacing python2 with python3?

**Comment by aclements** [comment]
> My motivation is to make sure the build work independent of python
> version, to make sure the debian package can build depend on python
> without a specific version number.

I'll go ahead and submit this because Python 3 is the future and all (to be clear, I actually quite like Python 3, I just don't think stable things should be translated without good reason since the translation may introduce bugs).

However, I'm afraid I still don't understand the motivation. This change does not make the build work independent of Python version; with this change it only works with Python 3. Also, my understanding of the policy is that the "python" package will continue to refer to Python 2, so it would be fine to declare a build dependency on the "python" package, just like how with this change it will need to depend on "python3".

**Pull request merged**
